config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :products, only: [:show, :new, :edit, :destroy, :create, :index,:update] do
    collection do
      get :search
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      get :compilation
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :users, only:[:show, :edit, :index, :update]

  resources :cards, only: [:new, :create, :show, :destroy] 
  
  resources :categories do
    collection do
      get :search
    end
  end
end

app/views/shared/_detail.html.haml
%nav.breadCrumbs
  %ul
    %li
      = link_to "#" do
        FURIMA
    %li
      %i{class:"fa fa-angle-right"}
    %li
      = link_to "#" do
        レディース
    %li
      %i{class:"fa fa-angle-right"}
    %li
      = link_to "#" do
        トップス
    %li
      %i{class:"fa fa-angle-right"}
    %li
      = link_to "#" do
        Tシャツ/カットソー(半袖/袖なし)
    %li
      %i{class:"fa fa-angle-right"}
    %li
      %pテスト
.Main
  .Main__show
    .Main__show__contLeft
    .Main__show__contRight
      .Main__show__contRight__topCont
        .Main__show__contRight__topCont__itemBox
          %h2.Main__show__contRight__topCont__itemBox__name
            = @product.name
          .Main__show__contRight__topCont__itemBox__body
            %ul
              %li
                #main-image
                  = image_tag @product.images[0].url.to_s
                  -if @product.orders.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
                %ul
                  -  @product.images.each do |image|
                    %li{class:"choice", id:"image-list"}
                      = image_tag image.url.to_s
          .Main__show__contRight__topCont__itemBox__price
            %span
              = "¥" + @product.price.to_s(:delimited)
            .Main__show__contRight__topCont__itemBox__price__tail
              %span
                （税込）
              %span
                送料込み

          - if user_signed_in? 
            - unless current_user.id == @product.user_id
              = link_to edit_product_path(@product.id), method: :get do
                .Main__show__contRight__topCont__itemBox__buy
                  購入画面に進む
          - else
            = link_to new_user_session_path do
              .Main__show__contRight__topCont__itemBox__buy
                購入画面に進む

          .Main__show__contRight__topCont__itemBox__detail
            =  @product.details
          .Main__show__contRight__topCont__itemBox__table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    =  @product.user.nickname
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#{@category_parent.name}","#"
                    %br= link_to "#{@category_child.name}","#"
                    = link_to "#{@category_grandchild.name}","#"
                %tr
                  %th
                    ブランド
                  %td
                    
                %tr
                  %th
                    商品のサイズ
                  %td
                    
                %tr
                  %th
                    商品の状態
                  %td
                    =  Condition.find(@product.condition_id).name
                %tr
                  %th
                    配送料の負担
                  %td
                    =  @product.fee_side 
                %tr
                  %th
                    発送元の地域
                  %td
                    = link_to "#" do
                      =  Prefecture.find(@product.prefecture_id).name
                %tr
                  %th
                    発送日の目安
                  %td
                    =  Day.find(@product.days_id).name
          .Main__show__contRight__topCont__itemBox__aria
            %ul
              %li{class:"optionalBtn likeBtn",id:"likeBtn"}
                %i{class:"fa fa-star"}
                  お気に入り 1
            %ul.option
              %li{class:"optionalBtn"}
                = link_to "#" do
                  %i{class:"fa fa-flag"}
                    不適切な商品の通報
        - if user_signed_in? && current_user.id == @product.user_id
          .Main__show__contRight__topCont__action
            %ul.action
              = link_to compilation_product_path(@product.id) do
                %li.Main__show__contRight__topCont__action__edit
                  商品の編集
              %li
                or
              = link_to product_path(@product.id), method: :delete, data: { confirm: '削除しますか？' } do
                %li.Main__show__contRight__topCont__action__delete
                  商品の削除

        .Main__show__contRight__topCont__comeBox
          %ul.comeCon
          %form{class:"new_comment", id:"new_comment",action:"#", acceptcharset:"UTF-8"}
            %input{name:"utf8",type:"hidden",value:"✓"}
            %input{name:"authenticity_token",type:"hidden",value:"mScUnLeaTbFM+ljkg74AFHGdvKa1EuMN2FoZXTgUichr7Kg2oLXvF1W2yCVI5jgVSPlYLDNhBewE3alqvXQVBw=="}
            %textarea{required:"required",name:"comment[body]",id:"comment_body"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
            %button{name:"button",type:"submit",class:"commentBtn"}
              %i{class:"fa fa-comment"}
                コメントする
      %ul.Main__show__contRight__links
        %li
          = link_to "#" do
            %i{class:"fa fa-angle-left"}
            %span
              前の商品
        %li
          = link_to "#" do
            %span
              後ろの商品
            %i{class:"fa fa-angle-right"}
      .Main__show__contRight__items
        = link_to "#" do
          レディースをもっと見る
        .Main__show__contRight__items__lists
          .Main__show__contRight__items__lists__list
            = link_to "#" do
              %figure{class:"productList--img"}
                = image_tag src="https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png"
              .Main__show__contRight__items__lists__list__body
                %h3{class:"name"}
                  product1
                .Main__show__contRight__items__lists__list__body__details
                  %ul
                    %li
                      10000円
                    %li
                      %i:{class:"fa fa-star likeIcon"}
                        1
                  %p
                    (税込)

app/views/shared/_error-messages.html.haml
- if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/shared/_footer.html.haml
%footer.Bottom
  %ul.Bottom__contents
    %li.Bottom__contents__menu
      %h2.Bottom__contents__menu__head
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要（運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    %li.Bottom__contents__menu
      %h2.Bottom__contents__menu__head
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    %li.Bottom__contents__menu
      %h2.Bottom__contents__menu__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            お知らせ
  .foologo
    = link_to "#" do
      = image_tag src="logo-white.png"
    %p© FURIMA

app/views/shared/_header.html.haml
%header.Top
  .Top__innerTop
    .Top__innerTop__main
      %h1.Logo
        = link_to "/" do
          = image_tag src="logo.png"
      .Top__innerTop__main__seach
        = form_with url: search_products_path, local: true, class: "Top__innerTop__main__seach__box", method: :get do |f|
          = f.text_field :keyword, placeholder: "キーワードから探す", class: "Top__innerTop__main__seach__box__text"
          = icon('fas', 'search', class: "Top__innerTop__main__seach__box__image")
          = f.submit "", class: "Top__innerTop__main__seach__box__btn"
    .Mokuji
      %ul.Mokuji__themeLeft
        %li.Mokuji__themeLeft__item.Mokuji__themeLeft__item--one
          = link_to "#", id: 'categoBtn' do
            カテゴリー
          #tree_menu
            %ul.categoryTree
              - @parents.each do |parent|
                %li.category_parent
                  = link_to "#" do
                    %input{type: "button", value: "#{parent.name}", name: "#{parent.id}", class: "parent_btn"}
              %li.category_parent
                = link_to "#" do
                  %input{type: "button", value: "全てのカテゴリー", id: "all_btn"}
            %ul.categoryTree-child
            %ul.categoryTree-grandchild

        %li.Mokuji__themeLeft__item
          = link_to "#" , id:"brandBtn"do
            ブランド
      
      %ul.Mokuji__themeRight
        - if user_signed_in?
          %li.Mokuji__themeRight__item.Mokuji__themeRight__item--log
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          %li.Mokuji__themeRight__item.Mokuji__themeRight__item--new
            = link_to user_path(current_user) do
              = current_user.nickname
        - else
          %li.Mokuji__themeRight__item.Mokuji__themeRight__item--log
            = link_to new_user_session_path do
              ログイン
          %li.Mokuji__themeRight__item.Mokuji__themeRight__item--new
            = link_to new_user_registration_path do
              新規会員登録

app/views/shared/_product.html.haml
%nav.breadCrumbs
  %ul
    %li
      %a{href:"#"}
        FURIMA
    %li
      %i{class:"fa fa-angle-right"}
    %li
      %a{href:"#"}
        レディース
    %li
      %i{class:"fa fa-angle-right"}
    %li
      %a{href:"#"}
        トップス
    %li
      %i{class:"fa fa-angle-right"}
    %li
      %a{href:"#"}
        Tシャツ/カットソー(半袖/袖なし)
    %li
      %i{class:"fa fa-angle-right"}
    %li
      %pテスト
.Main
  .Main__show
    .Main__show__contLeft
    .Main__show__contRight
      .Main__show__contRight__topCont
        .Main__show__contRight__topCont__itemBox
          %h2.Main__show__contRight__topCont__itemBox__name
            テスト
          .Main__show__contRight__topCont__itemBox__body
            %ul
              %li
                = image_tag src="https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/18/beef.JPG"
                %ul
                  %li
                    = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/18/beef.JPG", size: "75x75"
          .Main__show__contRight__topCont__itemBox__price
            %span
              ¥10000
            .Main__show__contRight__topCont__itemBox__price__tail
              %span
                （税込）
              %span
                送料込み  
          .Main__show__contRight__topCont__itemBox__detail
            テストテストテストテスト
          .Main__show__contRight__topCont__itemBox__table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    あああ
                %tr
                  %th
                    カテゴリー
                  %td
                    %a{href:"#"}
                      レディース
                    %br/
                    %a{href:"#"}
                      トップス
                    %br/
                    %a{href:"#"}
                      Tシャツ/カットソー(半袖/袖なし)
                %tr
                  %th
                    ブランド
                  %td
                    
                %tr
                  %th
                    商品のサイズ
                  %td
                    
                %tr
                  %th
                    商品の状態
                  %td
                    新品/未使用
                %tr
                  %th
                    配送料の負担
                  %td
                    送料込み（出品者負担）
                %tr
                  %th
                    発送元の地域
                  %td
                    %a{href:"#"}
                      北海道
                %tr
                  %th
                    発送日の目安
                  %td
                    1-2日で発送
          .Main__show__contRight__topCont__itemBox__aria
            %ul
              %li{class:"optionalBtn likeBtn",id:"likeBtn"}
                %i{class:"fa fa-star"}
                  お気に入り 1
            %ul.option
              %li{class:"optionalBtn"}
                %a{href:"#"}
                  %i{class:"fa fa-flag"}
                    不適切な商品の通報
        .Main__show__contRight__topCont__comeBox
          %ul.comeCon
          %form{class:"new_comment", id:"new_comment",action:"#", acceptcharset:"UTF-8"}
            %input{name:"utf8",type:"hidden",value:"✓"}
            %input{name:"authenticity_token",type:"hidden",value:"mScUnLeaTbFM+ljkg74AFHGdvKa1EuMN2FoZXTgUichr7Kg2oLXvF1W2yCVI5jgVSPlYLDNhBewE3alqvXQVBw=="}
            %textarea{required:"required",name:"comment[body]",id:"comment_body"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
            %button{name:"button",type:"submit",class:"commentBtn"}
              %i{class:"fa fa-comment"}
                コメントする
      %ul.Main__show__contRight__links
        %li
          %a{href:"#"}
            %i{class:"fa fa-angle-left"}
            %span
              前の商品
        %li
          %a{href:"#"}
            %span
              後ろの商品
            %i{class:"fa fa-angle-right"}
      .Main__show__contRight__items
        %a{href:"#"}
          レディースをもっと見る
        .Main__show__contRight__items__lists
          .Main__show__contRight__items__lists__list
            %a{href:"/products/1"}
              %figure{class:"productList--img"}
                = image_tag src="https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png"
              .Main__show__contRight__items__lists__list__body
                %h3{class:"name"}
                  product1
                .Main__show__contRight__items__lists__list__body__details
                  %ul
                    %li
                      10000円
                    %li
                      %i:{class:"fa fa-star likeIcon"}
                        1
                  %p
                    (税込)

app/views/shared/_purchase.html.haml
.Purchase
  .Purchase__all
    .Purchase__all__menu
      %section.Purchase__all__menu__one
        %h2
          購入内容確認
      %section.Purchase__all__menu__two
        .Purchase__all__menu__two__gazo
          .Purchase__all__menu__two__gazo__left
            %figure.Purchase__all__menu__two__gazo__left__box
              = image_tag src="https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/18/beef.JPG" , alt: "beef"
          .Purchase__all__menu__two__gazo__right
            %p.name
              ビーフ
            %p.kakaku
              %span.mozi
                送料込み (税込)
              %span.suuzi
                ￥１０,０００
      %section.Purchase__all__menu__three
        .Purchase__all__menu__three__money
          %span
            支払い金額
          %span
            ￥１０,０００
      %section.Purchase__all__menu__four
        .Purchase__all__menu__four__pay
          .Purchase__all__menu__four__pay__payOne
            %h3.Purchase__all__menu__four__pay__payone__payTwo
              支払い方法
          = link_to "#", {class:"Registration"} do
            %svg{"aria-hidden" => "true", :fill => "#0095ee", "fill-rule" => "evenodd", height:"20", viewbox:"0 0 24 24", width:"20"}
              %path{:d => "M17.51,11.3H12.7v-5a.7.7,0,0,0-1.4,0v5h-5a.7.7,0,0,0,0,1.4h5v4.81a.7.7,0,0,0,1.4,0V12.7h4.81a.7.7,0,0,0,0-1.4Z"}
              %path{:d => "M12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Zm0,18.6A8.6,8.6,0,1,1,20.6,12,8.61,8.61,0,0,1,12,20.6Z"}
            %span
              登録してください
      %section.Purchase__all__menu__five
        .Purchase__all__menu__five__place
          .Purchase__all__menu__five__place__placeOne
            %h3.Purchase__all__menu__five__place__placeone__placeTwo
              配送先
          = link_to "#", {class:"Registration"} do
            %svg{"aria-hidden" => "true", :fill => "#0095ee", "fill-rule" => "evenodd", height:"20", viewbox:"0 0 24 24", width:"20"}
              %path{:d => "M17.51,11.3H12.7v-5a.7.7,0,0,0-1.4,0v5h-5a.7.7,0,0,0,0,1.4h5v4.81a.7.7,0,0,0,1.4,0V12.7h4.81a.7.7,0,0,0,0-1.4Z"}
              %path{:d => "M12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Zm0,18.6A8.6,8.6,0,1,1,20.6,12,8.61,8.61,0,0,1,12,20.6Z"}
            %span
              登録してください
      %section.Purchase__all__menu__six
        .Purchase__all__menu__six__purchase
          %p
            配送先と支払い方法の入力を完了してください。
          = link_to buy_product_purchases_path(@product.id) do
            .Purchase__all__menu__six__purchase__botan 
              購入する

      