config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :products, only: [:show, :new, :edit, :destroy, :create, :index,:update] do
    collection do
      get :search
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      get :compilation
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :users, only:[:show, :edit, :index, :update]

  resources :cards, only: [:new, :create, :show, :destroy] 
  
  resources :categories do
    collection do
      get :search
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'
  before_action :set_card, only: [:destroy, :show]

  def new
    @card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if @card.exists?

  end

  def create
    # 前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)

    # 後ほどトークン作成処理を行いますが、そちらの完了の有無でフラッシュメッセージを表示させます。
    if params["payjp_token"].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
    # 無事トークン作成された場合のアクション(こっちが本命のアクション)
    # まずは生成したトークンから、顧客情報と紐付け、PAY.JP管理サイトに登録
      customer = Payjp::Customer.create(
        card: params["payjp_token"],
        metadata: {user_id: current_user.id} #最悪なくてもOK！
      )
      # 今度はトークン化した情報を自アプリのCredit_cardsテーブルに登録！
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      # 無事、トークン作成とともにcredit_cardsテーブルに登録された場合、createビューが表示されるように条件分岐
      if @card.save
        #もしcreateビューを作成しない場合はredirect_toなどで表示ビューを指定
      else
        redirect_to action: "create"
      end
    end
  end

  def show
    # ログイン中のユーザーのクレジットカード登録の有無を判断
    if @card.blank?
      # 未登録なら新規登録画面に
      redirect_to action: "new" 
    else
      # 前前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      # ログインユーザーのクレジットカード情報からPay.jpに登録されているカスタマー情報を引き出す
      customer = Payjp::Customer.retrieve(@card.customer_id)
      # カスタマー情報からカードの情報を引き出す
      @customer_card = customer.cards.retrieve(@card.card_id)
      ## 有効期限'月'を定義
      @exp_month = @customer_card.exp_month.to_s
      ## 有効期限'年'を定義
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end

  def destroy
    # ログイン中のユーザーのクレジットカード登録の有無を判断
    if @card.blank?
      # 未登録なら新規登録画面に
      redirect_to action: "new"
    else
      # 前前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :secret_key)
      # ログインユーザーのクレジットカード情報からPay.jpに登録されているカスタマー情報を引き出す
      customer = Payjp::Customer.retrieve(@card.customer_id)
      # そのカスタマー情報を消す
      customer.delete
      @card.delete
      # 削除が完了しているか判断
      if @card.destroy
      # 削除完了していればdestroyのビューに移行
      else
        # 削除されなかった場合flashメッセージを表示させて、showのビューに移行
        redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end
  private
  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.haml
.create
  .create__frame
    .create__frame__message
      登録が完了しました。
    %ul.create__frame__btns
      -# マイページに戻るパスを指定
      %li.my_page_link
        = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"
      -# のちに実装する、登録クレジットカード詳細表示(showアクション)に行くパスを指定
      %li.cards_index_link
        = link_to "登録カード一覧", card_path(current_user.id), class: "cards_index_link__btn"

app/views/cards/destroy.html.haml
.destoroy
  .destoroy__frame
    .destoroy__frame__message
      削除が完了しました。
    %ul.destoroy__frame__btns
      %li.credit_card_new_link
        = link_to "クレジットカード新規登録", new_card_path, class: "credit_card_new_link__btn"
      %li.my_page_link
        = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"

app/views/cards/new.html.haml
.card_add 
  .title クレジットカード情報入力

  -#form_tagメソッドでcreateアクションに入力情報を渡します。
  = form_tag(cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
    .number-details
      .card-number カード番号
      %span.must_check 必須
    .number
      = text_field_tag 'payment_card_no', "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
    .expirationdate
      .expirationdate__details
        .date 有効期限
        %span.must_check 必須
      .expirationdate__choice
        .month
          %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
            %option{value: "1"} 01
            %option{value: "2"} 02
            %option{value: "3"} 03
            %option{value: "4"} 04
            %option{value: "5"} 05
            %option{value: "6"} 06
            %option{value: "7"} 07
            %option{value: "8"} 08
            %option{value: "9"} 09
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          .month-details 月
        .year
          %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
            %option{value: "2020"} 20
            %option{value: "2021"} 21
            %option{value: "2022"} 22
            %option{value: "2023"} 23
            %option{value: "2024"} 24
            %option{value: "2025"} 25
            %option{value: "2026"} 26
            %option{value: "2027"} 27
            %option{value: "2028"} 28
            %option{value: "2029"} 29
            %option{value: "2030"} 30
          .year-details 年

    .securitycode
      .securitycode__details
        .securitycode-details__title セキュリティコード
        %span.must_check 必須
      .securitycode__cardsecurity
        = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
    .add 
      = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button" 

app/views/cards/show.html.haml
.show
  .show__frame
    .show__frame__title
      登録クレジットカード情報
    .credit_card__list
      .credit_card__list__title
        クレジットカード一覧
      .credit_card__list__frame
        .credit_card_info
          .credit_card_info__brand
          .credit_card_info__numbers
            .number

              = "**** **** **** " + @customer_card.last4
            .expiration_date
              .expiration_date__title
                有効期限
              .expiration_date__info
                
                = @exp_month + " / " + @exp_year
        .destroy__function
          .destroy__function__link
            
            = link_to card_path, method: :delete, class: "destroy__function__link__btn" do 
              削除する
      .payment-details
        = link_to "支払い方法について >", "", class: "payment-details__btn"