config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :products, only: [:show, :new, :edit, :destroy, :create, :index,:update] do
    collection do
      get :search
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      get :compilation
    end

    resource :purchases do
      member do
        get  "buy"
        post "pay"
      end
    end
  end

  resources :users, only:[:show, :edit, :index, :update]

  resources :cards, only: [:new, :create, :show, :destroy] 
  
  resources :categories do
    collection do
      get :search
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

  belongs_to :category, foreign_key: 'category_id'

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 } 
  validates :details, presence: true, length: { maximum: 1000 } 
  validates :fee_side, presence: true
  validates :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 300,less_than: 9999999}
  validates_associated :images
  validates :prefecture_id, presence: true
  validates :condition_id, presence: true
  validates :days_id, presence: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :day
  has_many :orders, dependent: :destroy

  def self.search(search)
    if search != ""
      Product.where('name LIKE(?) or details LIKE(?)', "%#{search}", "%#{search}%")
    else
      Product.all
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_parents

  def index
    @products = Product.order("created_at DESC").first(5)
  end

  def new
    @product = Product.new
    @product.images.new
    
    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children

  end

  def create
    @product = Product.new(product_params)

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    if @product.save
      redirect_to root_path
    else
        @product.images.new
        render :new
    end
  end

  def destroy
    product = Product.find(params[:id])
    if product.user_id == current_user.id
      if product.destroy
      else
        redirect_to root_path, alert: "削除が失敗しました"
      end
    end
  end

  def show
    @product = Product.find(params[:id])

    @category_id = @product.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end

  def search
    @products = Product.search(params[:keyword]).order("created_at DESC")
  end

  def edit
    @product = Product.find(params[:id])
  end


  def compilation
    @product = Product.find(params[:id])
    @images = Image.where(product_id: params[:id])
    @product.images.new

    grandchild_category = @product.category
    child_category = grandchild_category.parent

    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    @product = Product.find(params[:id])
    @images = Image.where(product_id: params[:id])
    
    grandchild_category = @product.category
    child_category = grandchild_category.parent

    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
    if @product.update_attributes(product_params)
      redirect_to "/"
    else
      render action: :compilation
    end
  end

  private
  
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def product_params
    params.require(:product).permit(:prefecture_id, :days_id, :condition_id, :category_id, :name, :details, :price, :condition, :fee_side, :origin, :days, images_attributes: [:url, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/compilation.html.haml
.Listing
  = link_to root_path do
    .Logo
      = image_tag 'logo.png',class: 'Logo__image'
  = form_with model: @product, local: true do |f|
    .Product
      = render 'shared/error-messages', model: f.object
      .Product__image
        %p.Product__image__title 
          出品画像 
          %span
            必須
        #previews
          - if @images.present?
            - @images.each_with_index do |img,n|
              = image_tag ("#{img.url}"),class: "image-show",data:{index: n}
          #image-select-btn
            image select
        #delete_button_field
          - if @images.present?
            - @images.each_with_index do |img,n|
              .js-remove{data: {index: n}} 削除
        %p.Product__image__detail 最大5枚までアップロードできます
        #image-file-fileds
          -# = f.fields_for :images, @product.images.build do |i|
          = f.fields_for :images do |i|
            = i.file_field :url, class: 'Product__image__submit',data:{index: i.index}
            - if i.object.persisted?
              = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
          -# - if @product.persisted?
          -#   .js-file_group{"data-index" => "#{@product.images.count}"}
          -#   = file_field_tag :url, name: "product[images_attributes][#{@product.images.count}][url]", class: 'js-file'
            
      .Product__name
        %p.Product__name__title 
          商品名
          %span
            必須
        = f.text_field :name, class: 'Product__name__text', placeholder: '40文字まで'

      .Product__explanation
        %p.Product__explanation__title 
          商品の説明
          %span
            必須
        = f.text_area :details, class: 'Product__explanation__text', placeholder: '商品の説明（必須 1000文字以内）'
        //文字数カウントはJSで行います。

      .Product__detail
        .Product__detail__title 商品の詳細
        .Product__detail__category
        = f.label 'カテゴリー', class: 'Product__detail__category__label'
        %span.Product__detail__category__require
          必須
        .Product__detail__category__select
          .Product__detail__category__select__box
            = f.select :parent_name, @category_parent_array, {selected:@product.category.parent.parent.name}, { class: 'Product__detail__category__select__box--form', id: 'parent_category'}
          .Product__detail__category__select__box#children_wrapper
            = f.select :child_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.parent.id}),{}, {class: 'Product__detail__category__select__box--form', id: 'child_category'}
          .Product__detail__category__select__box#grandchildren_wrapper
            = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.id}),{}, {class: 'Product__detail__category__select__box--form', id: 'grandchild_category'}
        .Product__detail__brand
          %p.Product__detail__brand__title
            ブランド
            %span
              任意
          = f.text_field :brand, class: 'Product__detail__brand__text', placeholder: '例）シャネル'
        
        .Product__detail__status
          %p.Product__detail__status__title
            商品の状態
            %span
              必須
          .Product__detail__status__select
            = f.collection_select :condition_id, Condition.all, :id, :name,{prompt: "選択してください"} , {class: 'Product__detail__status__select__form'}
      .Product__delivery
        .Product__delivery__title 商品の配送
        .Product__delivery__burden 
          %p.Product__delivery__burden__title
            配送料の負担
            %span
              必須
          .Product__delivery__burden__select
            = f.select :fee_side, options_for_select(["送料込み(出品者負担)", "着払い(購入者負担)"]), {prompt: "選択してください"}, {class: 'Product__delivery__burden__select__form'}

        .Product__delivery__region
          %p.Product__delivery__region__title
            発送元の地域
            %span
              必須
          .Product__delivery__region__select
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: 'Product__delivery__region__select__form'}
      
        .Product__delivery__day
          %p.Product__delivery__day__title
            発送までの日数
            %span
              必須
          .Product__delivery__day__select
            = f.collection_select :days_id, Day.all, :id, :name, {prompt: "選択してください"}, {class: 'Product__delivery__day__select__form'}

      .Product__price
        .Product__price__title 価格 (¥300 ~ 9,999,999)
        .Product__price__sale
          %p.Product__price__sale__title
            販売価格
            %span
              必須
          %span{class: "Product__price__sale__symbol"}
            ¥
          = f.text_field :price, class: 'Product__price__sale__form', placeholder: '0'
      
      .Product__btn
        = f.submit '出品する', class: 'Product__btn__submit'
        = link_to 'もどる', root_path, class: "Product__btn__return"
  
  .End
    .End__copy ©FURIMA
    

app/views/products/create.html.haml
.contents.row
  .success
    %h3 投稿が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/products/destroy.html.haml
.contents.row
  .success
    %h3 削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/products/edit.html.haml
= render 'shared/header'
= render partial: 'shared/purchase'
= render 'shared/footer'

app/views/products/index.html.haml
=render 'shared/header'
.Top-page
  .Image
    .Image__content
      .Image__content__message 人生を変えるフリマアプリ
      %p.Image__content__text
        FURIMAはだれでもかんたんに出品・購入できる 
        %br
        フリマアプリです
      .Image__content__link
        = link_to image_tag(src= "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "Image__content__link__apple"), "#"
        = link_to image_tag(src= "google-play-badge.png", class: "Image__content__link__google"), "#"

  .Reason
    .Reason__title FURIMAが選ばれる3つの理由
    %hr.Reason__line{size: "4", noshade: "", color: "#3CCACE"}
    %ul.Reason__lists
      %li.Reason__lists__one
        .Reason__lists__one__content
          = image_tag 'pict-reason-01.jpg',class: 'Reason__lists__one__content__image'
          .Reason__lists__one__content__num 1
        %p.Reason__lists__one__title 
          %span.Reason__lists__one__title--blue 3分 
          ですぐに出品
        %p.Reason__lists__one__text
          スマホで入力するだけで簡単に出品で
          %br
          きる！

      %li.Reason__lists__two
        .Reason__lists__two__content
          = image_tag 'pict-reason-02.jpg',class: 'Reason__lists__two__content__image'
          .Reason__lists__two__content__num 2
        %p.Reason__lists__two__title 
          %span.Reason__lists__two__title--blue シンプル 
          で使いやすい
        %p.Reason__lists__three__text
          めんどくさい入力は必要なく、検索も
          %br
          購入もスムーズ！

      %li.Reason__lists__three
        .Reason__lists__three__content
          = image_tag 'pict-reason-03.jpg',class: 'Reason__lists__three__content__image'
          .Reason__lists__three__content__num 3
        %p.Reason__lists__three__title 
          手数料
          %span.Reason__lists__three__title--blue 業界最安
        %p.Reason__lists__three__text
          最大3%でお得に出品&購入！
    
  .Middle
    .Middle__content
      .Middle__content__message 会員数日本一位
      %p.Middle__content__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .Middle__content__link
        = link_to image_tag(src= "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "Middle__content__link__apple"), "#"
        = link_to image_tag(src= "google-play-badge.png", class: "Middle__content__link__google"), "#"
  
  .Feature
    .Feature__title FURIMAの特徴
    %hr.Feature__line{size: "4", noshade: "", color: "#3CCACE"}
    %ul.Feature__lists
      %li.Feature__lists__set
        = image_tag 'icon-01.png',class: 'Feature__lists__set__image'
        %p.Feature__lists__set__title 簡単に売り買いできる
        %p.Feature__lists__set__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      %li.Feature__lists__set
        = image_tag 'icon-03.png',class: 'Feature__lists__set__image'
        %p.Feature__lists__set__title 売上金は即日振込みに対応
        %p.Feature__lists__set__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

      %li.Feature__lists__set
        = image_tag 'icon-04.png',class: 'Feature__lists__set__image'
        %p.Feature__lists__set__title 様々な支払いに対応
        %p.Feature__lists__set__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .Product
    .Product__theme 新規投稿商品
    .Product__lists
      
      - @products.each do |product|
        = link_to product_path(product.id), method: :get do
          .Product__lists__set
            =image_tag product.images[0].url.to_s ,{class: "Product__lists__set__image"}
            .Product__lists__set__content
              .Product__lists__set__content__information
                .Product__lists__set__content__information__name  
                  = product.name
                .Product__lists__set__content__information__price 
                  = product.price.to_s(:delimited)  + "円"
                .Product__lists__set__content__information__tax 
                  (税込)
              .Product__lists__set__content__star 
                .Product__lists__set__content__star__icon
                  = icon("fa", "star") 
                .Product__lists__set__content__star__Evaluation 
                  1
            -if product.orders.present? 
              .items-box_photo__sold
                .items-box_photo__sold__inner
                  SOLD
  
  .Download
    .Download__message
      .Download__message__upper だれでもかんたん、人生を変えるフリマアプリ
      .Download__message__lower 今すぐ無料ダウンロード！
    .Download__link
      = link_to image_tag(src= "Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "Middle__content__link__apple"), "#"
      = link_to image_tag(src= "google-play-badge.png", class: "Middle__content__link__google"), "#"

- if user_signed_in?
  = link_to new_product_path do
    .Exhibition-btn
      .Exhibition-btn__name 出品する
      =image_tag(src= "icon_camera.png", class: "Exhibition-btn__image")
- else
  = link_to new_user_session_path do
    .Exhibition-btn
      .Exhibition-btn__name 出品する
      =image_tag(src= "icon_camera.png", class: "Exhibition-btn__image")

=render 'shared/footer'

app/views/products/new.html.haml
.Listing
  = link_to root_path do
    .Logo
      = image_tag 'logo.png',class: 'Logo__image'
  = form_with model: @product, local: true do |f|
    .Product
      = render 'shared/error-messages', model: f.object
      .Product__image
        %p.Product__image__title 
          出品画像 
          %span
            必須
        #previews
          #image-select-btn
            image select
        #delete_button_field
        %p.Product__image__detail 最大5枚までアップロードできます
        #image-file-fileds
          = f.fields_for :images, @product.images.build do |i|
            = i.file_field :url, class: 'Product__image__submit',data:{index: i.index}
            - if @product.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
          - if @product.persisted?
            .js-file_group{"data-index" => "#{@product.images.count}"}
            = file_field_tag :url, name: "product[images_attributes][#{@product.images.count}][url]", class: 'js-file'
            .js-remove 削除
            
      .Product__name
        %p.Product__name__title 
          商品名
          %span
            必須
        = f.text_field :name, class: 'Product__name__text', placeholder: '40文字まで'

      .Product__explanation
        %p.Product__explanation__title 
          商品の説明
          %span
            必須
        = f.text_area :details, class: 'Product__explanation__text', placeholder: '商品の説明（必須 1000文字以内）'
        //文字数カウントはJSで行います。

      .Product__detail
        .Product__detail__title 商品の詳細
        .Product__detail__category
        = f.label 'カテゴリー', class: 'Product__detail__category__label'
        %span.Product__detail__category__require
          必須
        .Product__detail__category__select
          .Product__detail__category__select__box
          = f.select :category_id, @category_parent_array, {}, {class: 'Product__detail__category__select__box--form', id: 'parent_category'}
          -# %i.fas.fa-chevron-down.Product__detail__category__select__box--arrow-down

        .Product__detail__brand
          %p.Product__detail__brand__title
            ブランド
            %span
              任意
          = f.text_field :brand, class: 'Product__detail__brand__text', placeholder: '例）シャネル'
        
        .Product__detail__status
          %p.Product__detail__status__title
            商品の状態
            %span
              必須
          .Product__detail__status__select
            = f.collection_select :condition_id, Condition.all, :id, :name,{prompt: "選択してください"} , {class: 'Product__detail__status__select__form'}
      .Product__delivery
        .Product__delivery__title 商品の配送
        .Product__delivery__burden 
          %p.Product__delivery__burden__title
            配送料の負担
            %span
              必須
          .Product__delivery__burden__select
            = f.select :fee_side, options_for_select(["送料込み(出品者負担)", "着払い(購入者負担)"]), {prompt: "選択してください"}, {class: 'Product__delivery__burden__select__form'}

        .Product__delivery__region
          %p.Product__delivery__region__title
            発送元の地域
            %span
              必須
          .Product__delivery__region__select
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "選択してください"}, {class: 'Product__delivery__region__select__form'}
      
        .Product__delivery__day
          %p.Product__delivery__day__title
            発送までの日数
            %span
              必須
          .Product__delivery__day__select
            = f.collection_select :days_id, Day.all, :id, :name, {prompt: "選択してください"}, {class: 'Product__delivery__day__select__form'}

      .Product__price
        .Product__price__title 価格 (¥300 ~ 9,999,999)
        .Product__price__sale
          %p.Product__price__sale__title
            販売価格
            %span
              必須
          %span{class: "Product__price__sale__symbol"}
            ¥
          = f.text_field :price, class: 'Product__price__sale__form', placeholder: '0'
      
      .Product__btn
        = f.submit '出品する', class: 'Product__btn__submit'
        = link_to 'もどる', root_path, class: "Product__btn__return"
  
  .End
    .End__copy ©FURIMA
    

app/views/products/search.html.haml
=render 'shared/header'
.Top-page
  .Product-search
    .Product-search__theme
      - if params[:keyword] == ""
        全商品
      - else
        = params[:keyword] + "の検索結果"
    .Product-search__lists
      - @products.each do |product|
        = link_to product_path(product.id), method: :get do
          .Product-search__lists__set
            =image_tag product.images[0].url.to_s ,{class: "Product-search__lists__set__image"}
            .Product-search__lists__set__content
              .Product-search__lists__set__content__information
                .Product-search__lists__set__content__information__name  
                  = product.name
                .Product-search__lists__set__content__information__price 
                  = product.price.to_s(:delimited)  + "円"
                .Product-search__lists__set__content__information__tax 
                  (税込)
              .Product-search__lists__set__content__star 
                .Product-search__lists__set__content__star__icon
                  = icon("fa", "star") 
                .Product-search__lists__set__content__star__Evaluation 
                  = 1
            -if product.orders.present? 
              .items-box_photo__sold
                .items-box_photo__sold__inner
                  SOLD

- if user_signed_in?
  = link_to new_product_path do
    .Exhibition-btn
      .Exhibition-btn__name 出品する
      =image_tag(src= "icon_camera.png", class: "Exhibition-btn__image")
- else
  = link_to new_user_session_path do
    .Exhibition-btn
      .Exhibition-btn__name 出品する
      =image_tag(src= "icon_camera.png", class: "Exhibition-btn__image")

=render 'shared/footer'

app/views/products/show.html.haml
= render 'shared/header'
= render 'layouts/notifications'
= render partial: 'shared/detail'
= render 'shared/footer'